# Generated by Django 3.0.5 on 2020-04-30 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCtoLN_SwapInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('refund_address', models.CharField(max_length=35)),
                ('bolt11_invoice', models.CharField(max_length=1000)),
                ('lockduration', models.IntegerField(default=1)),
                ('redeemblock', models.IntegerField(null=True)),
                ('final_address_pubkey', models.CharField(max_length=35, null=True)),
                ('preimage', models.CharField(max_length=500, null=True)),
                ('funding_transaction', models.CharField(max_length=1000, null=True)),
                ('redemption_transaction', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
