# Generated by Django 3.0.5 on 2020-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctoln_swapinvoice',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
