# Generated by Django 3.0.5 on 2020-05-08 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0002_btctoln_swapinvoice_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='btctoln_swapinvoice',
            name='amount_to_swap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='btctoln_swapinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='btctoln_swapinvoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
